### ISSUE TITLE
修改了ts，导致webpack一堆报错

### ISSUE THREAD

**Issue by baixiaoji** [baixiaoji/vue-ts#1]
```
Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4
    at successfulTypeScriptInstance (/Users/future/test-place/aaa/node_modules/ts-loader/dist/instances.js:155:15)
    at Object.getTypeScriptInstance (/Users/future/test-place/aaa/node_modules/ts-loader/dist/instances.js:51:12)
    at Object.loader (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:16:41)

 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.ts

```

**Comment by baixiaoji** [comment]
> Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4 at successfulTypeScriptInstance (/Users/future/test-place/aaa/node_modules/ts-loader/dist/instances.js:155:15) at Object.getTypeScriptInstance (/Users/future/test-place/aaa/node_modules/ts-loader/dist/instances.js:51:12) at Object.loader (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:16:41) @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.ts

npm install webpack@4 -D

**Comment by baixiaoji** [comment]
```
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.getEmitOutput (/Users/future/test-place/aaa/node_modules/ts-loader/dist/instances.js:190:40)
    at getEmit (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:198:37)
    at successLoader (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:34:11)
    at Object.loader (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:21:12)

 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.ts
```

**Comment by baixiaoji** [comment]
> Module build failed: TypeError: Cannot read property 'getEmitOutput' of null at Object.getEmitOutput (/Users/future/test-place/aaa/node_modules/ts-loader/dist/instances.js:190:40) at getEmit (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:198:37) at successLoader (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:34:11) at Object.loader (/Users/future/test-place/aaa/node_modules/ts-loader/dist/index.js:21:12) @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.ts

npm i -D vue-loader@14

**Comment by baixiaoji** [comment]
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/future/test-place/aaa/node_modules/webpack-dev-server/bin/webpack-dev-server.js:54:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by baixiaoji** [comment]
> module.js:471 throw err; ^ Error: Cannot find module 'webpack/bin/config-yargs' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (/Users/future/test-place/aaa/node_modules/webpack-dev-server/bin/webpack-dev-server.js:54:1) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3)


npm install webpack-cli@3  webpack-dev-server@3

https://github.com/mzgoddard/jest-webpack/issues/27

**Comment by baixiaoji** [comment]
```
place/aaa/node_modules/events/events.js/Users/future/test-place/aaa/node_modules/html-webpack-plugin/lib/compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
                                                  ^

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /Users/future/test-place/aaa/node_modules/html-webpack-plugin/lib/compiler.js:81:51
    at compile (/Users/future/test-place/aaa/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/future/test-place/aaa/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/future/test-place/aaa/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/future/test-place/aaa/node_modules/tapable/lib/Hook.js:154:20)
```

**Comment by baixiaoji** [comment]
> place/aaa/node_modules/events/events.js/Users/future/test-place/aaa/node_modules/html-webpack-plugin/lib/compiler.js:81 var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, { ^ TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function at /Users/future/test-place/aaa/node_modules/html-webpack-plugin/lib/compiler.js:81:51 at compile (/Users/future/test-place/aaa/node_modules/webpack/lib/Compiler.js:296:11) at hooks.afterCompile.callAsync.err (/Users/future/test-place/aaa/node_modules/webpack/lib/Compiler.js:553:14) at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/future/test-place/aaa/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1) at AsyncSeriesHook.lazyCompileHook (/Users/future/test-place/aaa/node_modules/tapable/lib/Hook.js:154:20)

npm i -D html-webpack-plugin@3
https://github.com/jantimon/html-webpack-plugin/issues/841
